# Generated by Django 4.2.1 on 2023-07-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0004_remove_todo_list_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_list',
            name='user_name',
            field=models.CharField(default='abdulmuhaimin', max_length=50),
            preserve_default=False,
        ),
    ]
